env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
parser: 
  "babel-eslint"
plugins:
  - react
  - babel
rules:
  func-names: ["error", "as-needed"]
  space-before-function-paren: ["error", "never"]
  max-len: ["error", 120]
  no-underscore-dangle: ["error", { "allow": ["_id", "_str"]}]
  no-plusplus: ["error", {"allowForLoopAfterthoughts": true}]
  import/no-unresolved: [2, { ignore: ["^meteor/"] }]
  comma-dangle: ["error", "only-multiline"]
  react/static-property-placement: ["error", "property assignment", {
    defaultProps: "static public field",
    propTypes: "static public field"
  }]

